"""Replacement studies: what is a better (or cheaper) model worth on one step?

A study runs a baseline preset, then the same setup with exactly one role swapped to a candidate
model: one configuration per (role, candidate), applied in every selected scenario that has that
role. Candidates may also be decision services ("ollaya:winnow:e4b", "jev:jev-latest"), which
replace the control decisions of scenarios that support a control policy. Everything else stays
fixed, so the report can attribute differences to that one step.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Literal

from pydantic import BaseModel, Field

from llm_arena.decisions.config import SERVICES
from llm_arena.runner.presets import ModelPreset
from llm_arena.scenarios.base import RoleRequirement, Scenario

DECISIONS = "decisions"  # study "role" of a decision-service swap


class StudyConfig(BaseModel):
    baseline: str = Field(description="the preset every configuration starts from (the baseline)")
    candidates: list[str] = Field(
        min_length=1, max_length=200, description="model references (or ollaya:/jev: decision models) to try"
    )
    roles: list[str] | None = Field(
        default=None, max_length=200, description="roles to swap (default: every role except the decision roles)"
    )
    decision_control: Literal["gate", "policy", "review"] = Field(
        default="gate", description="how a decision-service candidate controls the agent"
    )


class StudyTag(BaseModel):
    """Marks a configuration generated by a study, so the report can compare it with the baseline."""

    kind: Literal["baseline", "swap"]
    role: str | None = None
    candidate: str | None = None


def short(ref: str) -> str:
    base, _, settings = ref.partition("#")
    name = base.split(":", 1)[1] if ":" in base else base
    notes = [
        "no thinking" if s == "reasoning=none" else s.replace("reasoning=", "reasoning ")
        for s in settings.split(",")
        if s
    ]
    return f"{name} ({', '.join(notes)})" if notes else name


def expand(
    study: StudyConfig,
    scenarios: list[Scenario],
    profile: ModelPreset,
    can_do: Callable[[str, RoleRequirement], bool] = lambda candidate, role: True,
) -> list[dict[str, object]]:
    """The study's configurations as PipelineConfig data: the baseline first, then one per (role, candidate).
    `can_do(candidate, role)`: whether the candidate has the capabilities the role needs (e.g. vision)."""
    configs: list[dict[str, object]] = [{"name": "baseline", "preset": study.baseline, "study": {"kind": "baseline"}}]
    names = {"baseline"}

    def add(name: str, config: dict[str, object]) -> None:
        unique, n = name, 2
        while unique in names:
            unique, n = f"{name} {n}", n + 1
        names.add(unique)
        configs.append({"name": unique, "preset": study.baseline, **config})

    roles = study.roles or sorted({r.name for s in scenarios for r in s.roles if r.kind != "decision"})
    for candidate in study.candidates:
        service = candidate.split(":", 1)[0]
        if service in SERVICES:
            controlled = [s.name for s in scenarios if s.supports_decisions]
            if controlled:
                model = candidate.split(":", 1)[1]
                decisions = {"policy": service, "control": study.decision_control, f"{service}_model": model}
                add(f"{DECISIONS}→{model}", {"scenarios": controlled, "decisions": decisions,
                                              "study": {"kind": "swap", "role": DECISIONS, "candidate": candidate}})  # fmt: skip
            continue
        for role in roles:
            # Only where the role exists and the candidate differs from what the baseline already uses there.
            swapped = {
                s.name: {role: candidate}
                for s in scenarios
                for r in s.roles
                if r.name == role and profile.model_for(r.kind) != candidate and can_do(candidate, r)
            }
            if swapped:
                add(f"{role}→{short(candidate)}", {"scenarios": sorted(swapped), "scenario_roles": swapped,
                                                    "study": {"kind": "swap", "role": role, "candidate": candidate}})  # fmt: skip
    return configs
